[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false


[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "./tailwindcss -i ./styles.css -o ./dist/.stage/output.css --minify"]


